import type { Metadata } from "next";
import { ThemeProvider } from "@/providers/ThemeProvider";
import AppShell from "@/components/AppShell";
import { NavContainer } from "@/components/Nav";

import { Routes } from "@/utils/routes";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {

    return (
        <html lang="en">
            <body>
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange
                >
                    <AppShell
                        navigation={<NavContainer sections={Routes} />}
                    >
                        {children}
                    </AppShell>
                </ThemeProvider>
            </body>
        </html>
    );
}
